extends Node
class_name Enums


enum SIDE_DATA {FUEL_COST, DESCRIPTION, ACTIONS_LIST, AFTER_PLAY, ACTION_ICON}
enum ACTION {MOVE_TYPE, VALUE, MOVE_AREA, MOVE_INFO}
enum ACTION_TYPE {ATTACK, MOVE, SPECIAL}
enum ATTACK {MOVE_TYPE, VALUE, TARGET_AREA, ANIMATION_TYPE}
enum MOVE {MOVE_TYPE, DESTINATION}
enum SPECIAL {MOVE_TYPE, VALUE, TARGET_AREA, EFFECT_NAME, AFFECTED_TARGET}
enum EFFECT {EFFECT_NAME, ICON_NAME, WHEN_ACTIVE, ANIMATION_TO_PLAY, DESCRIPTION}
enum AFFECTED_TARGET {TARGET, ACTING_ACTOR}

enum CASSETTE_STATE {IN_DECK, IN_HAND_IDLE, HOVERED_OVER, DRAGGING, IN_SLOT}
enum BATTLE_POSITIONS {SLOW_DOWN, LINE_UP, OVERTAKE}

enum {PLAYER, ENEMY}
enum DurationType {
	NEXT_TURN,
	THIS_TURN,
	NEXT_CARD,
	NEXT_ACTION,
	NEXT_ATTACK,
	PERMANENT
}
